apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-harbor-images
spec:
  background: true
  validationFailureAction: Enforce
  rules:
    - name: only-harbor
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Images must come from Harbor 192.168.216.130."
        pattern:
          spec:
            containers:
              - image: "192.168.216.130/*"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privileged
spec:
  background: true
  validationFailureAction: Enforce
  rules:
    - name: no-privileged
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Privileged containers are not allowed."
        pattern:
          spec:
            containers:
              - =(securityContext):
                  =(privileged): false
