apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
        namespace: platform-dev
        replicas: "1"
      - env: staging
        namespace: platform-staging
        replicas: "2"
      - env: prod
        namespace: platform-prod
        replicas: "3"
  template:
    metadata:
      name: 'platform-{{env}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/Amine99x/Devsecops-Platform.git
        targetRevision: main
        path: kubernetes/environments/{{env}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
